### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by selfi-svg** [panchishin/storm-the-house#1]
Traceback (most recent call last):
  File "storm_the_house.py", line 17, in <module>
    keypress = pykeyboard.PyKeyboard() # the keyboard tool
AttributeError: module 'pykeyboard' has no attribute 'PyKeyboard'

shows up when i run

**Comment by panchishin** [comment]
strange.  Perhaps try changing the line to be `keypress = pyKeyboard()`
